name: 🐞 Bug Report
description: Create a report to help reproduce and resolve the bug.
title: "[Bug] "
labels: ["bug"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm these steps before submitting
      options:
        - label: "I have checked [FAQs](https://github.com/fla-org/flash-linear-attention/blob/main/FAQs.md) and existing issues for similar problems"
        - label: "Please report this bug in English to ensure wider understanding and support"

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: Provide a clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce the Bug
      description: |
        Please include a code sample that reproduces the issue you encountered. This can be a Colab link or a code snippet.
        If you have code snippets, error messages, or stack traces, please include them here as well.
        Important! Use code formatting to clearly present your code. See [GitHub's guide on code formatting](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting).
        Avoid using screenshots, as they can be difficult to read and do not allow others to easily copy and paste your code.
      placeholder: |
        Code snippets or steps to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Provide a clear and concise description of the expected results.
    validations:
      required: true

  - type: textarea
    id: environment-info
    attributes:
      label: Environment Information
      description: Please share your environment details, including Python version, Torch version, Triton version, and platform.
      value: |
        1. Torch:
        2. Triton:
    validations:
      required: true
